### ISSUE TITLE
[Question] How do those output-of-commands work?

### ISSUE THREAD

**Issue by ShadowKyogre** [ershov/tmux#1]
Hi there! Loving your fork of tmux so far. It allows for some pretty complex interfaces.

However, I'm a bit stuck on reworking one of my plain tmux shortcuts into a more intricate menu. What I want to do is unify creation and selection of sessions into one interface:

```
bind-key C tcl {
    choose-from-list \
    -val "<<new>>" \
    -val "<<new w/a pwd>>" \
    -list {*}[tcl { output-of-txt {list-sessions -F "#S"} } ] \
    -onselect {
        if { "$_" eq "<<new>>" } {
            command-prompt -p "new-session name"  "new-session -A -s %1"
        } elseif { "$_" eq "<<new w/a pwd>>" } {
            command-prompt -p "new-session name","new-session pwd" -I"","$HOME"  "new-session -A -s %1 -c %2"
        } else {
            attach-session -t "$_"
        }
    }
}
```

I also tried the example in the readme to set a sample list to no avail:

```
output-of-list { list-keys -t vi-copy }
```

If I  have the curly braces, I get this:

```
Tue Apr 26 08:13:36 2016 Error: invalid command name ":_output-divert"
```

If I don't, I get this:

```
Tue Apr 26 08:16:13 2016 Error: wrong # args: should be "output-of-list code"
```

**Comment by ershov** [comment]
Hi!

Thank you for your report.
I've looked into that and found out that I had broke this command during past re-work.

Please pull the latest 'master' for the fix.

For your case you most likely need to use `output-of-list` to have the lines split into the list rather than the whole output as a single string.

Also, you might want to have a look at `example_tcl_tmux.tcl` for some ideas and code samples.

**Comment by ShadowKyogre** [comment]
Pulled it and just gave the fixed version of my example a test run! Thanks a bunch for this!

**Comment by ershov** [comment]
Also, your command-prompt statement writes as follows:

```
command-prompt -p "new-session name,new-session pwd" -I ",~"  "new-session -A -s %1 -c %2"
```
